import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'


export const metadata: Metadata = {
  title: 'Booking.com __Clone',
  description: 'Generated by hajiali',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Head */}
        <Header />
        {children}
      </body>
    </html>
  )
}